apiVersion: apps/v1
kind: Deployment
metadata: 
  name: converter-deployment
  labels:
    app: converter-deployment
spec: 
  replicas: 4
  selector: 
    matchLabels: 
      app: converter-deployment
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 8
  template:
    metadata:
      labels:
        app: converter-deployment
    spec:
      containers:
        - name: converter-deployment
          image: blue143/converter
          envFrom:
            - configMapRef:
                name: converter-configmap
            - secretRef:
                name: converter-secret